#   config.yaml
#
#   This is a config file for the example data. It can be used as a
#   starting point for creating a custom config file for your project.
#   Please read the parameter descriptions at the bottom of this file.

# performance settings
performance:
    n_cpu: 72
    n_gpu: 1
    cuda_devices: [0]

# templates settings
templates:
    n_stations: 4
    channel: HHZ
    prepick: 3
    min_len: 15
    length_fixed: False

# pre_processing settings
pre_processing:
    highpass: 1.0
    lowpass: 4.0
    decimate: 4

# cross_correlation settings
cross_correlation:
    data_start: 2021-01-05
    data_stop: 2021-01-05
    cc_threshold: 0.7
    mad_threshold: 8
    combine_thresholds: True

# directories settings
directories:
    meta_dir: metadata
    event_dir: events
    template_dir: templates
    matches_dir: matches
    family_dir: event_families
    data_path: data_CX
    data_structure: "{data_path}/{year}/{net}/{sta}/{cha}.D/\
                     {net}.{sta}.{loc}.{cha}.D.{year}.{julday}"

# selection settings
selection:
    cc_criteria: [0.7, 0.7]
    mad_criteria: []
    max_t_diff: 10.0
    combine_criteria: True


#   parameter descriptions:
#
#   performance settings:
#       n_cpu (int, optional): maximum number of parallel processes to be
#           used. Defaults to the number of cpu cores.
#       n_gpu: (int, optional): maximum number of graphics cards to use. By
#           default, all graphics cards will be used.
#       cuda_devices: (list, optional): specify which CUDA devices should be
#           used. By default, the first 'n_gpu' devices will be used.
#
#   template settings:
#       n_stations (int, required): the number of stations for which to extract
#           templatewaveforms. These will be the closest available stations
#           to the event hypocenter.
#       channel (str, optional): channel code to be used. The use of multiple
#           channels is currently not supported. Defaults to 'HHZ'.
#       prepick (float, required): starttime of the template windows relative
#           to the estimated P-wave arrival in seconds.
#       min_len (float, required): minimum length of the template waveforms in
#           sec. The templates will be lengthened with 5 second increments for
#           increasing hypocentral distance.
#       length_fixed (bool, required): if set to True, all template waveforms
#            will have the same length determined by `min_len`.
#
#   pre-processing settings:
#       highpass (float, required): lower frequency in Hz of the bandpass
#           filter applied to both the templates (permanent) and continuous
#           data (upon loading).
#       lowpass (float, required): upper frequency in Hz of the bandpass filter
#           applied to both the templates (permanent) and continuous data (upon
#           loading).
#       decimate (int, required): the factor by which the sampling rate of the
#           data should be lowered (for faster computation). Decimation will be
#           applied permanently to the templates and dynamically to the
#           continuous data upon loading.
#
#   cross-correlation settings:
#       data_start (yyyy-mm-dd, required): starting date for cross-correlation
#           of the templates with the continous data.
#       data_stop (yyyy-mm-dd, required): last date to be included in the
#           cross-correlation.
#       cc_threshold (float, required): threshold of the absolute normalized
#           cross-correlation value.
#       mad_threshold (float, required): threshold of the normalized cross-
#           correlation value as a factor of the daily median absolute
#            deviation (MAD).
#       combine_thresholds (bool, required): if True, the highest of both
#           thresholds will be used. If False, the lowest of both will be used.
#
#   folders and file structure:
#   path names are defined either absolute, or relative to the project
#   folder containing this configuration file.
#       meta_dir (str): path to the metadata folder that holds the station
#           xml file `stations.xml` containing the station information.
#       event_dir (str): path to the folder where event information is
#           stored. Single event catalog files will be created here to
#           which the template files and event families can be traces back
#           to through their filenames.
#       template_dir (str): path to the folder where template waveforms
#           will be stored.
#       matches_dir (str): path to the folder where all matches to each
#           individual template waveform are stored.
#       family_dir (str): path to the folder where event detections that
#           exceed the selection criteria are stored for each template
#           event. Note that the same event can occur within multiple event
#           families.
#       data_path (str): path to the folder that holds the continuous data.
#       data_structure (str)): description of the data structure (folders &
#           filenames) within `data_path`. Placeholders can (and should) be
#           used to include the data folder, year, netowrk code, station
#           code, location code, channel code and the julian day in curly
#           brackets: {data_path}, {year}, {net}, {sta}, {loc}, {cha},
#           {loc}, {julday}.
#
#   event selection criteria:
#       cc_criteria (list of floats): selection criteria to define an event
#           in terms of the absolute normalized cross-correlation value.
#           For example: [0.7, 0.5] would mean that two simultaneous
#           matches with absolute cross-correlation values >= 0.7 & >= 0.5
#           on two different stations are required within the time range
#           `max_t_diff`. Use an empty list `[]` if no cc-criteria should
#           be applied.
#       mad_criteria (list of floats): selection criteria to define an
#           event in terms of a factor of the daily median absolute
#           deviation (MAD) of the normalized cross-correlation function.
#           For example: [10, 8] would mean that two simultaneous matches
#           with 10x and 8x the daily MAD value are required within the
#           time range `max_t_diff`. Use an empty list `[]` if no MAD-
#           criteria should be applied.
#       max_t_diff (float): maximum time difference in seconds between
#           individual detections that allows them to be called
#           simultaneous for the purpose of the selection criteria defined
#           above. Note that the time difference relates to the estimated
#           origin time of the detections and not the actual occurrence of
#           the template waveforms, since these would depend on the
#           stations hypocentral distance.
#       combine_criteria (bool): if True, both the `cc_criteria` as well as
#           the `mad_criteria` need to be met. If set to False an event is
#           defined when either of both criteria are met.
